# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20171102_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='my_date_field',
        ),
    ]
